/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/head/head.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/core/src/animation/animation_transition';
import * as import9 from '@angular/core/src/animation/animation_sequence_player';
import * as import10 from '@angular/core/src/animation/animation_styles';
import * as import11 from '@angular/core/src/animation/animation_style_util';
import * as import12 from '@angular/core/src/animation/animation_keyframe';
import * as import13 from '@angular/core/src/animation/animation_player';
import * as import14 from '@angular/core/src/linker/view_container';
import * as import15 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import16 from '@angular/core/src/change_detection/change_detection_util';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from '@angular/common/src/directives/ng_if';
export class Wrapper_HeadComponent {
  /*private*/ _eventHandler:Function;
  context:import0.HeadComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.HeadComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_HeadComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_HeadComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.HeadComponent>;
  _HeadComponent_0_3:Wrapper_HeadComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HeadComponent_Host0,renderType_HeadComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'head_box',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_HeadComponent0(this.viewUtils,this,0,this._el_0);
    this._HeadComponent_0_3 = new Wrapper_HeadComponent();
    this.compView_0.create(this._HeadComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._HeadComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HeadComponent) && (0 === requestNodeIndex))) { return this._HeadComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HeadComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const HeadComponentNgFactory:import7.ComponentFactory<import0.HeadComponent> = new import7.ComponentFactory<import0.HeadComponent>('head_box',View_HeadComponent_Host0,import0.HeadComponent);
const styles_HeadComponent:any[] = ([] as any[]);
var HeadComponent_heroState_states:any = {
  'inactive': {
    'top': '-100%',
    'bottom': '100%'
  }
  ,
  'active': {
    'top': '0',
    'bottom': '64px'
  }
  ,
  '*': {}
}
;
function HeadComponent_heroState_factory(view:import1.AppView<any>,element:any,currentState:any,nextState:any):import8.AnimationTransition {
  var previousPlayers:any = view.animationContext.getAnimationPlayers(element,((nextState == 'void')? (null as any): 'heroState'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = HeadComponent_heroState_states['*'];
  var startStateStyles:any = HeadComponent_heroState_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = HeadComponent_heroState_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  if (((player == (null as any)) && ((currentState == 'inactive') && (nextState == 'active')))) {
      player = new import9.AnimationSequencePlayer([view.renderer.animate(element,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[startStateStyles])),import11.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import12.AnimationKeyframe(0,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}]))),
        new import12.AnimationKeyframe(1,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),300,0,'ease-in',previousPlayers)]);
    totalTime = 300;
  }
  if (((player == (null as any)) && ((currentState == 'active') && (nextState == 'inactive')))) {
      player = new import9.AnimationSequencePlayer([view.renderer.animate(element,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[startStateStyles])),import11.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import12.AnimationKeyframe(0,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}]))),
        new import12.AnimationKeyframe(1,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),300,0,'ease-in',previousPlayers)]);
    totalTime = 300;
  }
  if ((player == (null as any))) { (player = new import13.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    player.destroy();
    import11.renderStyles(element,view.renderer,import11.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  new import9.AnimationSequencePlayer(previousPlayers).destroy();
  import11.renderStyles(element,view.renderer,import11.clearStyles(startStateStyles));
  view.animationContext.queueAnimation(element,'heroState',player);
  return new import8.AnimationTransition(player,currentState,nextState,totalTime);
}
var HeadComponent_heroState2_states:any = {
  'inactive': {'height': '0'},
  'active': {'height': '*'},
  '*': {}
}
;
function HeadComponent_heroState2_factory(view:import1.AppView<any>,element:any,currentState:any,nextState:any):import8.AnimationTransition {
  var previousPlayers:any = view.animationContext.getAnimationPlayers(element,((nextState == 'void')? (null as any): 'heroState2'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = HeadComponent_heroState2_states['*'];
  var startStateStyles:any = HeadComponent_heroState2_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = HeadComponent_heroState2_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  if (((player == (null as any)) && ((currentState == 'inactive') && (nextState == 'active')))) {
      player = new import9.AnimationSequencePlayer([view.renderer.animate(element,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[startStateStyles])),import11.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import12.AnimationKeyframe(0,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}]))),
        new import12.AnimationKeyframe(1,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),500,0,'ease-in',previousPlayers)]);
    totalTime = 500;
  }
  if (((player == (null as any)) && ((currentState == 'active') && (nextState == 'inactive')))) {
      player = new import9.AnimationSequencePlayer([view.renderer.animate(element,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[startStateStyles])),import11.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import12.AnimationKeyframe(0,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}]))),
        new import12.AnimationKeyframe(1,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),500,0,'ease-in',previousPlayers)]);
    totalTime = 500;
  }
  if ((player == (null as any))) { (player = new import13.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    player.destroy();
    import11.renderStyles(element,view.renderer,import11.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  new import9.AnimationSequencePlayer(previousPlayers).destroy();
  import11.renderStyles(element,view.renderer,import11.clearStyles(startStateStyles));
  view.animationContext.queueAnimation(element,'heroState2',player);
  return new import8.AnimationTransition(player,currentState,nextState,totalTime);
}
var HeadComponent_topchange_states:any = {
  'toptype1': {'left': '0'},
  'toptype2': {'left': '-100%'},
  'toptype3': {'left': '-200%'},
  '*': {}
}
;
function HeadComponent_topchange_factory(view:import1.AppView<any>,element:any,currentState:any,nextState:any):import8.AnimationTransition {
  var previousPlayers:any = view.animationContext.getAnimationPlayers(element,((nextState == 'void')? (null as any): 'topchange'));
  var collectedStyles:any = {};
  var player:any = (null as any);
  var totalTime:any = 0;
  var defaultStateStyles:any = HeadComponent_topchange_states['*'];
  var startStateStyles:any = HeadComponent_topchange_states[currentState];
  if ((startStateStyles == (null as any))) { (startStateStyles = defaultStateStyles); }
  var endStateStyles:any = HeadComponent_topchange_states[nextState];
  if ((endStateStyles == (null as any))) { (endStateStyles = defaultStateStyles); }
  if (((player == (null as any)) && ((currentState == 'toptype1') && (nextState == 'toptype2')))) {
      player = new import9.AnimationSequencePlayer([view.renderer.animate(element,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[startStateStyles])),import11.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import12.AnimationKeyframe(0,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}]))),
        new import12.AnimationKeyframe(1,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),500,0,'ease-in',previousPlayers)]);
    totalTime = 500;
  }
  if (((player == (null as any)) && ((currentState == 'toptype2') && (nextState == 'toptype3')))) {
      player = new import9.AnimationSequencePlayer([view.renderer.animate(element,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[startStateStyles])),import11.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import12.AnimationKeyframe(0,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}]))),
        new import12.AnimationKeyframe(1,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),500,0,'ease-in',previousPlayers)]);
    totalTime = 500;
  }
  if (((player == (null as any)) && ((currentState == 'toptype3') && (nextState == 'toptype2')))) {
      player = new import9.AnimationSequencePlayer([view.renderer.animate(element,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[startStateStyles])),import11.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import12.AnimationKeyframe(0,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}]))),
        new import12.AnimationKeyframe(1,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),500,0,'ease-in',previousPlayers)]);
    totalTime = 500;
  }
  if (((player == (null as any)) && ((currentState == 'toptype2') && (nextState == 'toptype1')))) {
      player = new import9.AnimationSequencePlayer([view.renderer.animate(element,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[startStateStyles])),import11.balanceAnimationKeyframes(collectedStyles,endStateStyles,[
        new import12.AnimationKeyframe(0,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}]))),
        new import12.AnimationKeyframe(1,new import10.AnimationStyles(import11.collectAndResolveStyles(collectedStyles,[{}])))
      ]
    ),500,0,'ease-in',previousPlayers)]);
    totalTime = 500;
  }
  if ((player == (null as any))) { (player = new import13.NoOpAnimationPlayer()); }
  player.onDone(():void => {
    player.destroy();
    import11.renderStyles(element,view.renderer,import11.prepareFinalAnimationStyles(startStateStyles,endStateStyles));
  });
  new import9.AnimationSequencePlayer(previousPlayers).destroy();
  import11.renderStyles(element,view.renderer,import11.clearStyles(startStateStyles));
  view.animationContext.queueAnimation(element,'topchange',player);
  return new import8.AnimationTransition(player,currentState,nextState,totalTime);
}
var renderType_HeadComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_HeadComponent,{
  heroState: HeadComponent_heroState_factory,
  heroState2: HeadComponent_heroState2_factory,
  topchange: HeadComponent_topchange_factory
}
);
export class View_HeadComponent0 extends import1.AppView<import0.HeadComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _vc_5:import14.ViewContainer;
  _TemplateRef_5_5:any;
  _NgIf_5_6:import15.Wrapper_NgIf;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _vc_7:import14.ViewContainer;
  _TemplateRef_7_5:any;
  _NgIf_7_6:import15.Wrapper_NgIf;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _text_87:any;
  _el_88:any;
  _text_89:any;
  _text_90:any;
  _el_91:any;
  _text_92:any;
  _text_93:any;
  _el_94:any;
  _text_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _text_102:any;
  _el_103:any;
  _text_104:any;
  _text_105:any;
  _text_106:any;
  _el_107:any;
  _text_108:any;
  _el_109:any;
  _text_110:any;
  _el_111:any;
  _text_112:any;
  _text_113:any;
  _el_114:any;
  _text_115:any;
  _text_116:any;
  _el_117:any;
  _text_118:any;
  _text_119:any;
  _text_120:any;
  _text_121:any;
  /*private*/ _expr_128:any;
  /*private*/ _expr_129:any;
  /*private*/ _expr_130:any;
  /*private*/ _expr_131:any;
  /*private*/ _expr_132:any;
  /*private*/ _expr_133:any;
  /*private*/ _expr_134:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_HeadComponent0,renderType_HeadComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_128 = import16.UNINITIALIZED;
    this._expr_129 = import16.UNINITIALIZED;
    this._expr_130 = import16.UNINITIALIZED;
    this._expr_131 = import16.UNINITIALIZED;
    this._expr_132 = import16.UNINITIALIZED;
    this._expr_133 = import16.UNINITIALIZED;
    this._expr_134 = import16.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','head_box'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','head_top'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._vc_5 = new import14.ViewContainer(5,3,this,this._anchor_5);
    this._TemplateRef_5_5 = new import17.TemplateRef_(this,5,this._anchor_5);
    this._NgIf_5_6 = new import15.Wrapper_NgIf(this._vc_5.vcRef,this._TemplateRef_5_5);
    this._text_6 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_3,(null as any));
    this._vc_7 = new import14.ViewContainer(7,3,this,this._anchor_7);
    this._TemplateRef_7_5 = new import17.TemplateRef_(this,7,this._anchor_7);
    this._NgIf_7_6 = new import15.Wrapper_NgIf(this._vc_7.vcRef,this._TemplateRef_7_5);
    this._text_8 = this.renderer.createText(this._el_3,'\n      ',(null as any));
    this._text_9 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','head_bottom'),(null as any));
    this._text_11 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_1,'ul',new import3.InlineArray2(2,'class','head_ul_list'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'page1',(null as any));
    this._el_16 = import3.createRenderElement(this.renderer,this._el_14,'div',new import3.InlineArray2(2,'class','head_list_bt'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'page1下部显示',(null as any));
    this._text_18 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_12,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'page2',(null as any));
    this._el_21 = import3.createRenderElement(this.renderer,this._el_19,'div',new import3.InlineArray2(2,'class','head_list_bt'),(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'page2下部显示',(null as any));
    this._text_23 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_12,'li',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'page3',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'div',new import3.InlineArray2(2,'class','head_list_bt'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'page3下部显示',(null as any));
    this._text_28 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._text_29 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','head_bottom_box'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._el_32 = import3.createRenderElement(this.renderer,this._el_30,'ul',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'\n          ',(null as any));
    this._el_34 = import3.createRenderElement(this.renderer,this._el_32,'li',new import3.InlineArray2(2,'class','diandian_li dian_li_1'),(null as any));
    this._text_35 = this.renderer.createText(this._el_32,'\n          ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_32,'li',new import3.InlineArray2(2,'class','diandian_li dian_li_2'),(null as any));
    this._text_37 = this.renderer.createText(this._el_32,'\n          ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_32,'li',new import3.InlineArray2(2,'class','diandian_li dian_li_3'),(null as any));
    this._text_39 = this.renderer.createText(this._el_32,'\n        ',(null as any));
    this._text_40 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_30,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'\n        ',(null as any));
    this._text_43 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_30,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'\n        ',(null as any));
    this._text_46 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._el_47 = import3.createRenderElement(this.renderer,this._el_30,'div',new import3.InlineArray2(2,'class','head_bottom_up'),(null as any));
    this._text_48 = this.renderer.createText(this._el_30,'\n      ',(null as any));
    this._text_49 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_50 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'class','head_start'),(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'\n      ',(null as any));
    this._el_53 = import3.createRenderElement(this.renderer,this._el_51,'div',new import3.InlineArray2(2,'class','head_button_start'),(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'\n        ',(null as any));
    this._el_55 = import3.createRenderElement(this.renderer,this._el_53,'div',new import3.InlineArray2(2,'class','head_button_text'),(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'START',(null as any));
    this._text_57 = this.renderer.createText(this._el_53,'\n      ',(null as any));
    this._text_58 = this.renderer.createText(this._el_51,'\n      ',(null as any));
    this._el_59 = import3.createRenderElement(this.renderer,this._el_51,'div',new import3.InlineArray2(2,'class','head_button_stop'),(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'\n        ',(null as any));
    this._el_61 = import3.createRenderElement(this.renderer,this._el_59,'div',new import3.InlineArray2(2,'class','head_button_text'),(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'STOP',(null as any));
    this._text_63 = this.renderer.createText(this._el_59,'\n      ',(null as any));
    this._text_64 = this.renderer.createText(this._el_51,'\n    ',(null as any));
    this._text_65 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_66 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray4(4,'class','head_box_more','id','head_box_more'),(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'\n      ',(null as any));
    this._el_68 = import3.createRenderElement(this.renderer,this._el_66,'div',new import3.InlineArray2(2,'class','head_box_list'),(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._el_70 = import3.createRenderElement(this.renderer,this._el_68,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'123123',(null as any));
    this._text_72 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._el_73 = import3.createRenderElement(this.renderer,this._el_68,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_74 = this.renderer.createText(this._el_73,'123123',(null as any));
    this._text_75 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._el_76 = import3.createRenderElement(this.renderer,this._el_68,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_77 = this.renderer.createText(this._el_76,'123123',(null as any));
    this._text_78 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._el_79 = import3.createRenderElement(this.renderer,this._el_68,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'123123',(null as any));
    this._text_81 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._el_82 = import3.createRenderElement(this.renderer,this._el_68,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_83 = this.renderer.createText(this._el_82,'123123',(null as any));
    this._text_84 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._el_85 = import3.createRenderElement(this.renderer,this._el_68,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_86 = this.renderer.createText(this._el_85,'123123',(null as any));
    this._text_87 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._el_88 = import3.createRenderElement(this.renderer,this._el_68,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_89 = this.renderer.createText(this._el_88,'123123',(null as any));
    this._text_90 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._el_91 = import3.createRenderElement(this.renderer,this._el_68,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_92 = this.renderer.createText(this._el_91,'123123',(null as any));
    this._text_93 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._el_94 = import3.createRenderElement(this.renderer,this._el_68,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_95 = this.renderer.createText(this._el_94,'123123',(null as any));
    this._text_96 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._el_97 = import3.createRenderElement(this.renderer,this._el_68,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_98 = this.renderer.createText(this._el_97,'123123',(null as any));
    this._text_99 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._el_100 = import3.createRenderElement(this.renderer,this._el_68,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_101 = this.renderer.createText(this._el_100,'123123',(null as any));
    this._text_102 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._el_103 = import3.createRenderElement(this.renderer,this._el_68,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_104 = this.renderer.createText(this._el_103,'123123',(null as any));
    this._text_105 = this.renderer.createText(this._el_68,'\n      ',(null as any));
    this._text_106 = this.renderer.createText(this._el_66,'\n      ',(null as any));
    this._el_107 = import3.createRenderElement(this.renderer,this._el_66,'div',new import3.InlineArray2(2,'class','headmorebox'),(null as any));
    this._text_108 = this.renderer.createText(this._el_107,'\n        ',(null as any));
    this._el_109 = import3.createRenderElement(this.renderer,this._el_107,'div',new import3.InlineArray2(2,'class','headmoreall'),(null as any));
    this._text_110 = this.renderer.createText(this._el_109,'\n          ',(null as any));
    this._el_111 = import3.createRenderElement(this.renderer,this._el_109,'div',new import3.InlineArray2(2,'class','headmoretop'),(null as any));
    this._text_112 = this.renderer.createText(this._el_111,'STATUS',(null as any));
    this._text_113 = this.renderer.createText(this._el_109,'\n          ',(null as any));
    this._el_114 = import3.createRenderElement(this.renderer,this._el_109,'div',new import3.InlineArray2(2,'class','headmoremid'),(null as any));
    this._text_115 = this.renderer.createText(this._el_114,'Electronic fan has stopped working',(null as any));
    this._text_116 = this.renderer.createText(this._el_109,'\n          ',(null as any));
    this._el_117 = import3.createRenderElement(this.renderer,this._el_109,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_118 = this.renderer.createText(this._el_109,'\n        ',(null as any));
    this._text_119 = this.renderer.createText(this._el_107,'\n      ',(null as any));
    this._text_120 = this.renderer.createText(this._el_66,'\n    ',(null as any));
    this._text_121 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_47,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_47));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_107,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_107));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._text_102,
      this._el_103,
      this._text_104,
      this._text_105,
      this._text_106,
      this._el_107,
      this._text_108,
      this._el_109,
      this._text_110,
      this._el_111,
      this._text_112,
      this._text_113,
      this._el_114,
      this._text_115,
      this._text_116,
      this._el_117,
      this._text_118,
      this._text_119,
      this._text_120,
      this._text_121
    ]
    ),[
      disposable_0,
      disposable_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import18.NgIf) && (5 === requestNodeIndex))) { return this._NgIf_5_6.context; }
    if (((token === import17.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import18.NgIf) && (7 === requestNodeIndex))) { return this._NgIf_7_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_128:any = this.context.style1;
    if (import3.checkBinding(throwOnChange,this._expr_128,currVal_128)) {
      var animationTransition_heroState:any = this.componentType.animations['heroState'](this,this._el_1,((this._expr_128 == import16.UNINITIALIZED)? 'void': this._expr_128),((currVal_128 == import16.UNINITIALIZED)? 'void': currVal_128));
      this._expr_128 = currVal_128;
    }
    const currVal_129:any = this.context.topchange;
    if (import3.checkBinding(throwOnChange,this._expr_129,currVal_129)) {
      var animationTransition_topchange:any = this.componentType.animations['topchange'](this,this._el_12,((this._expr_129 == import16.UNINITIALIZED)? 'void': this._expr_129),((currVal_129 == import16.UNINITIALIZED)? 'void': currVal_129));
      this._expr_129 = currVal_129;
    }
    const currVal_133:any = this.context.style2;
    if (import3.checkBinding(throwOnChange,this._expr_133,currVal_133)) {
      var animationTransition_heroState2:any = this.componentType.animations['heroState2'](this,this._el_68,((this._expr_133 == import16.UNINITIALIZED)? 'void': this._expr_133),((currVal_133 == import16.UNINITIALIZED)? 'void': currVal_133));
      this._expr_133 = currVal_133;
    }
    const currVal_5_0_0:any = (this.context.leftbtn != '');
    this._NgIf_5_6.check_ngIf(currVal_5_0_0,throwOnChange,false);
    this._NgIf_5_6.ngDoCheck(this,this._anchor_5,throwOnChange);
    const currVal_7_0_0:any = (this.context.rightbtn != '');
    this._NgIf_7_6.check_ngIf(currVal_7_0_0,throwOnChange,false);
    this._NgIf_7_6.ngDoCheck(this,this._anchor_7,throwOnChange);
    this._vc_5.detectChangesInNestedViews(throwOnChange);
    this._vc_7.detectChangesInNestedViews(throwOnChange);
    const currVal_130:any = import3.inlineInterpolate(1,'head_bottom_dian ',this.context.dianhover,'');
    if (import3.checkBinding(throwOnChange,this._expr_130,currVal_130)) {
      this.renderer.setElementProperty(this._el_32,'className',currVal_130);
      this._expr_130 = currVal_130;
    }
    const currVal_131:any = import3.inlineInterpolate(1,'up_or_down_icon head_up_or_downleft ',this.context.rotate_1801,'');
    if (import3.checkBinding(throwOnChange,this._expr_131,currVal_131)) {
      this.renderer.setElementProperty(this._el_41,'className',currVal_131);
      this._expr_131 = currVal_131;
    }
    const currVal_132:any = import3.inlineInterpolate(1,'up_or_down_icon head_up_or_downright ',this.context.rotate_1801,'');
    if (import3.checkBinding(throwOnChange,this._expr_132,currVal_132)) {
      this.renderer.setElementProperty(this._el_44,'className',currVal_132);
      this._expr_132 = currVal_132;
    }
    const currVal_134:any = import3.inlineInterpolate(1,'headmorebottom ',this.context.rotate_180,'');
    if (import3.checkBinding(throwOnChange,this._expr_134,currVal_134)) {
      this.renderer.setElementProperty(this._el_117,'className',currVal_134);
      this._expr_134 = currVal_134;
    }
  }
  destroyInternal():void {
    this._vc_5.destroyNestedViews();
    this._vc_7.destroyNestedViews();
  }
  detachInternal():void {
    var animationTransition_heroState:any = this.componentType.animations['heroState'](this,this._el_1,this._expr_128,'void');
    var animationTransition_topchange:any = this.componentType.animations['topchange'](this,this._el_12,this._expr_129,'void');
    var animationTransition_heroState2:any = this.componentType.animations['heroState2'](this,this._el_68,this._expr_133,'void');
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 5)) { return new View_HeadComponent1(this.viewUtils,this,5,this._anchor_5,this._vc_5); }
    if ((nodeIndex == 7)) { return new View_HeadComponent2(this.viewUtils,this,7,this._anchor_7,this._vc_7); }
    return (null as any);
  }
  handleEvent_47(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.changestyle()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_107(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.changestyle2()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_HeadComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import14.ViewContainer) {
    super(View_HeadComponent1,renderType_HeadComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import16.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray2(2,'class','head_top_btnleft'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'',this.parentView.context.leftbtn,'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.changeheadleft()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_HeadComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import14.ViewContainer) {
    super(View_HeadComponent2,renderType_HeadComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import16.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray2(2,'class','head_top_btnright'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = import3.inlineInterpolate(1,'',this.parentView.context.rightbtn,'');
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.changeheadright()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}