/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/core/src/linker/view_container';
import * as import9 from '../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-container.ngfactory';
import * as import10 from '../../app/head/head.component';
import * as import11 from './head/head.component.ngfactory';
import * as import12 from '../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import13 from '../../app/foot/foot.component';
import * as import14 from './foot/foot.component.ngfactory';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/core/src/linker/component_factory_resolver';
import * as import17 from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';
import * as import18 from '@angular/router/src/router_outlet_map';
import * as import19 from '@angular/router/src/router';
import * as import20 from '../../app/service/navigation.service';
import * as import21 from '../../app/service/menus.service';
import * as import22 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as import23 from '@ng-bootstrap/ng-bootstrap/modal/modal-container';
import * as import24 from '@angular/router/src/directives/router_outlet';
export class Wrapper_AppComponent {
  /*private*/ _eventHandler:Function;
  context:import0.AppComponent;
  /*private*/ _changed:boolean;
  constructor() {
    this._changed = false;
    this.context = new import0.AppComponent();
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.AppComponent>;
  _AppComponent_0_3:Wrapper_AppComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent_Host0,renderType_AppComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'my-app',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_AppComponent0(this.viewUtils,this,0,this._el_0);
    this._AppComponent_0_3 = new Wrapper_AppComponent();
    this.compView_0.create(this._AppComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._AppComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const AppComponentNgFactory:import7.ComponentFactory<import0.AppComponent> = new import7.ComponentFactory<import0.AppComponent>('my-app',View_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_AppComponent,{});
export class View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _vc_3:import8.ViewContainer;
  _TemplateRef_3_5:any;
  _NgbModalContainer_3_6:import9.Wrapper_NgbModalContainer;
  _text_4:any;
  _el_5:any;
  compView_5:import1.AppView<import10.HeadComponent>;
  _HeadComponent_5_3:import11.Wrapper_HeadComponent;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _vc_9:import8.ViewContainer;
  _RouterOutlet_9_5:import12.Wrapper_RouterOutlet;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  compView_12:import1.AppView<import13.FootComponent>;
  _FootComponent_12_3:import14.Wrapper_FootComponent;
  _text_13:any;
  _text_14:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_AppComponent0,renderType_AppComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray2(2,'id','main'),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._vc_3 = new import8.ViewContainer(3,1,this,this._anchor_3);
    this._TemplateRef_3_5 = new import15.TemplateRef_(this,3,this._anchor_3);
    this._NgbModalContainer_3_6 = new import9.Wrapper_NgbModalContainer(this.injector(3),this.renderer,this._vc_3.vcRef,this.parentView.injectorGet(import16.ComponentFactoryResolver,this.parentIndex),this.parentView.injectorGet(import17.NgbModalStack,this.parentIndex));
    this._text_4 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_1,'head_box',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_5 = new import11.View_HeadComponent0(this.viewUtils,this,5,this._el_5);
    this._HeadComponent_5_3 = new import11.Wrapper_HeadComponent();
    this.compView_5.create(this._HeadComponent_5_3.context);
    this._text_6 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_7 = import3.createRenderElement(this.renderer,this._el_1,'div',new import3.InlineArray2(2,'class','content'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_7,'router-outlet',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._vc_9 = new import8.ViewContainer(9,7,this,this._el_9);
    this._RouterOutlet_9_5 = new import12.Wrapper_RouterOutlet(this.parentView.injectorGet(import18.RouterOutletMap,this.parentIndex),this._vc_9.vcRef,this.parentView.injectorGet(import16.ComponentFactoryResolver,this.parentIndex),(null as any));
    this._text_10 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_11 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_1,'foot_box',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_12 = new import14.View_FootComponent0(this.viewUtils,this,12,this._el_12);
    this._FootComponent_12_3 = new import14.Wrapper_FootComponent(this.parentView.injectorGet(import19.Router,this.parentIndex),this.parentView.injectorGet(import20.NavService,this.parentIndex),this.parentView.injectorGet(import21.menuService,this.parentIndex),this.parentView.injectorGet(import22.NgbModal,this.parentIndex));
    this.compView_12.create(this._FootComponent_12_3.context);
    this._text_13 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import23.NgbModalContainer) && (3 === requestNodeIndex))) { return this._NgbModalContainer_3_6.context; }
    if (((token === import10.HeadComponent) && (5 === requestNodeIndex))) { return this._HeadComponent_5_3.context; }
    if (((token === import24.RouterOutlet) && (9 === requestNodeIndex))) { return this._RouterOutlet_9_5.context; }
    if (((token === import13.FootComponent) && (12 === requestNodeIndex))) { return this._FootComponent_12_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgbModalContainer_3_6.ngDoCheck(this,this._anchor_3,throwOnChange);
    this._HeadComponent_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    this._RouterOutlet_9_5.ngDoCheck(this,this._el_9,throwOnChange);
    this._FootComponent_12_3.ngDoCheck(this,this._el_12,throwOnChange);
    this._vc_3.detectChangesInNestedViews(throwOnChange);
    this._vc_9.detectChangesInNestedViews(throwOnChange);
    this.compView_5.internalDetectChanges(throwOnChange);
    this.compView_12.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_3.destroyNestedViews();
    this._vc_9.destroyNestedViews();
    this.compView_5.destroy();
    this.compView_12.destroy();
    this._RouterOutlet_9_5.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 3)) { return new View_AppComponent1(this.viewUtils,this,3,this._anchor_3,this._vc_3); }
    return (null as any);
  }
}
class View_AppComponent1 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import8.ViewContainer) {
    super(View_AppComponent1,renderType_AppComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): ([] as any[])),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}