/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@ng-bootstrap/ng-bootstrap/alert/alert.module';
import * as import6 from '@ng-bootstrap/ng-bootstrap/buttons/radio.module';
import * as import7 from '@ng-bootstrap/ng-bootstrap/collapse/collapse.module';
import * as import8 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar.module';
import * as import9 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip.module';
import * as import10 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead.module';
import * as import11 from '@ng-bootstrap/ng-bootstrap/accordion/accordion.module';
import * as import12 from '@ng-bootstrap/ng-bootstrap/carousel/carousel.module';
import * as import13 from '@angular/forms/src/directives';
import * as import14 from '@angular/forms/src/form_providers';
import * as import15 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker.module';
import * as import16 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown.module';
import * as import17 from '@ng-bootstrap/ng-bootstrap/modal/modal.module';
import * as import18 from '@ng-bootstrap/ng-bootstrap/pagination/pagination.module';
import * as import19 from '@ng-bootstrap/ng-bootstrap/popover/popover.module';
import * as import20 from '@ng-bootstrap/ng-bootstrap/rating/rating.module';
import * as import21 from '@ng-bootstrap/ng-bootstrap/tabset/tabset.module';
import * as import22 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker.module';
import * as import23 from '@ng-bootstrap/ng-bootstrap/index';
import * as import24 from '@angular/router/src/router_module';
import * as import25 from '../../app/app-routing';
import * as import26 from '../../app/home/home-routing.module';
import * as import27 from '../../app/home/home.module';
import * as import28 from '../../app/setup/setup-routing.module';
import * as import29 from '../../app/shared/shared.module';
import * as import30 from '../../app/setup/setup.module';
import * as import31 from '@angular/common/src/localization';
import * as import32 from '@angular/core/src/application_init';
import * as import33 from '@angular/core/src/testability/testability';
import * as import34 from '@angular/core/src/application_ref';
import * as import35 from '@angular/core/src/linker/compiler';
import * as import36 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import37 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import38 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import39 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import40 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import41 from '@angular/core/src/animation/animation_queue';
import * as import42 from '@angular/core/src/linker/view_utils';
import * as import43 from '@angular/platform-browser/src/browser/title';
import * as import44 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import45 from '@ng-bootstrap/ng-bootstrap/modal/modal-stack';
import * as import46 from '@ng-bootstrap/ng-bootstrap/modal/modal';
import * as import47 from '@ng-bootstrap/ng-bootstrap/alert/alert-config';
import * as import48 from '@ng-bootstrap/ng-bootstrap/progressbar/progressbar-config';
import * as import49 from '@ng-bootstrap/ng-bootstrap/tooltip/tooltip-config';
import * as import50 from '@ng-bootstrap/ng-bootstrap/typeahead/typeahead-config';
import * as import51 from '@ng-bootstrap/ng-bootstrap/accordion/accordion-config';
import * as import52 from '@ng-bootstrap/ng-bootstrap/carousel/carousel-config';
import * as import53 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-calendar';
import * as import54 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-i18n';
import * as import55 from '@ng-bootstrap/ng-bootstrap/datepicker/ngb-date-parser-formatter';
import * as import56 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-service';
import * as import57 from '@ng-bootstrap/ng-bootstrap/datepicker/datepicker-config';
import * as import58 from '@ng-bootstrap/ng-bootstrap/dropdown/dropdown-config';
import * as import59 from '@ng-bootstrap/ng-bootstrap/pagination/pagination-config';
import * as import60 from '@ng-bootstrap/ng-bootstrap/popover/popover-config';
import * as import61 from '@ng-bootstrap/ng-bootstrap/rating/rating-config';
import * as import62 from '@ng-bootstrap/ng-bootstrap/tabset/tabset-config';
import * as import63 from '@ng-bootstrap/ng-bootstrap/timepicker/timepicker-config';
import * as import64 from '@angular/common/src/location/location';
import * as import65 from '@angular/router/src/url_tree';
import * as import66 from '@angular/router/src/router_outlet_map';
import * as import67 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import68 from '@angular/router/src/router_preloader';
import * as import69 from '../../app/service/menus.service';
import * as import70 from '../../app/service/navigation.service';
import * as import71 from '@angular/core/src/di/injector';
import * as import72 from '../node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory';
import * as import73 from '../node_modules/@ng-bootstrap/ng-bootstrap/tooltip/tooltip.ngfactory';
import * as import74 from '../node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory';
import * as import75 from '../node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory';
import * as import76 from '../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-backdrop.ngfactory';
import * as import77 from '../node_modules/@ng-bootstrap/ng-bootstrap/modal/modal-window.ngfactory';
import * as import78 from '../node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory';
import * as import79 from './home/home.component.ngfactory';
import * as import80 from './setup/setup.component.ngfactory';
import * as import81 from './setup/settings-menu.component.ngfactory';
import * as import82 from './setup/wizardsMenu/wizards.component.ngfactory';
import * as import83 from './setup/abc.ngfactory';
import * as import84 from './app.component.ngfactory';
import * as import85 from '@angular/core/src/application_tokens';
import * as import86 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import87 from '@angular/platform-browser/src/dom/events/key_events';
import * as import88 from '@angular/core/src/zone/ng_zone';
import * as import89 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import90 from '@angular/common/src/location/platform_location';
import * as import91 from '@angular/common/src/location/location_strategy';
import * as import92 from '../../app/home/home.component';
import * as import93 from '../../app/setup/setup.component';
import * as import94 from '../../app/setup/settings-menu.component';
import * as import95 from '../../app/setup/wizardsMenu/wizards.component';
import * as import96 from '../../app/setup/abc';
import * as import97 from '@angular/router/src/url_handling_strategy';
import * as import98 from '@angular/router/src/route_reuse_strategy';
import * as import99 from '@angular/router/src/router';
import * as import100 from '@angular/core/src/console';
import * as import101 from '@angular/core/src/i18n/tokens';
import * as import102 from '@angular/core/src/error_handler';
import * as import103 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import104 from '@angular/platform-browser/src/dom/animation_driver';
import * as import105 from '@angular/core/src/render/api';
import * as import106 from '@angular/core/src/security';
import * as import107 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import108 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import109 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import110 from '@angular/router/src/router_config_loader';
import * as import111 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _NgbAlertModule_3:import5.NgbAlertModule;
  _NgbButtonsModule_4:import6.NgbButtonsModule;
  _NgbCollapseModule_5:import7.NgbCollapseModule;
  _NgbProgressbarModule_6:import8.NgbProgressbarModule;
  _NgbTooltipModule_7:import9.NgbTooltipModule;
  _NgbTypeaheadModule_8:import10.NgbTypeaheadModule;
  _NgbAccordionModule_9:import11.NgbAccordionModule;
  _NgbCarouselModule_10:import12.NgbCarouselModule;
  _InternalFormsSharedModule_11:import13.InternalFormsSharedModule;
  _FormsModule_12:import14.FormsModule;
  _NgbDatepickerModule_13:import15.NgbDatepickerModule;
  _NgbDropdownModule_14:import16.NgbDropdownModule;
  _NgbModalModule_15:import17.NgbModalModule;
  _NgbPaginationModule_16:import18.NgbPaginationModule;
  _NgbPopoverModule_17:import19.NgbPopoverModule;
  _NgbRatingModule_18:import20.NgbRatingModule;
  _NgbTabsetModule_19:import21.NgbTabsetModule;
  _NgbTimepickerModule_20:import22.NgbTimepickerModule;
  _NgbRootModule_21:import23.NgbRootModule;
  _ROUTER_FORROOT_GUARD_22:any;
  _RouterModule_23:import24.RouterModule;
  _CrisisCenterRoutingModule_24:import25.CrisisCenterRoutingModule;
  _HomeRoutingModule_25:import26.HomeRoutingModule;
  _HomeModule_26:import27.HomeModule;
  _SetupRoutingModule_27:import28.SetupRoutingModule;
  _SharedModule_28:import29.SharedModule;
  _Setup_29:import30.Setup;
  _AppModule_30:import1.AppModule;
  __LOCALE_ID_31:any;
  __NgLocalization_32:import31.NgLocaleLocalization;
  _ErrorHandler_33:any;
  _ApplicationInitStatus_34:import32.ApplicationInitStatus;
  _Testability_35:import33.Testability;
  _ApplicationRef__36:import34.ApplicationRef_;
  __ApplicationRef_37:any;
  __Compiler_38:import35.Compiler;
  __APP_ID_39:any;
  __DOCUMENT_40:any;
  __HAMMER_GESTURE_CONFIG_41:import36.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_42:any[];
  __EventManager_43:import37.EventManager;
  __DomSharedStylesHost_44:import38.DomSharedStylesHost;
  __AnimationDriver_45:any;
  __DomRootRenderer_46:import39.DomRootRenderer_;
  __NgProbeToken_47:any[];
  __RootRenderer_48:any;
  __DomSanitizer_49:import40.DomSanitizerImpl;
  __Sanitizer_50:any;
  __AnimationQueue_51:import41.AnimationQueue;
  __ViewUtils_52:import42.ViewUtils;
  __IterableDiffers_53:any;
  __KeyValueDiffers_54:any;
  __SharedStylesHost_55:any;
  __Title_56:import43.Title;
  __RadioControlRegistry_57:import44.RadioControlRegistry;
  __NgbModalStack_58:import45.NgbModalStack;
  __NgbModal_59:import46.NgbModal;
  __NgbAlertConfig_60:import47.NgbAlertConfig;
  __NgbProgressbarConfig_61:import48.NgbProgressbarConfig;
  __NgbTooltipConfig_62:import49.NgbTooltipConfig;
  __NgbTypeaheadConfig_63:import50.NgbTypeaheadConfig;
  __NgbAccordionConfig_64:import51.NgbAccordionConfig;
  __NgbCarouselConfig_65:import52.NgbCarouselConfig;
  __NgbCalendar_66:import53.NgbCalendarGregorian;
  __NgbDatepickerI18n_67:import54.NgbDatepickerI18nDefault;
  __NgbDateParserFormatter_68:import55.NgbDateISOParserFormatter;
  __NgbDatepickerService_69:import56.NgbDatepickerService;
  __NgbDatepickerConfig_70:import57.NgbDatepickerConfig;
  __NgbDropdownConfig_71:import58.NgbDropdownConfig;
  __NgbPaginationConfig_72:import59.NgbPaginationConfig;
  __NgbPopoverConfig_73:import60.NgbPopoverConfig;
  __NgbRatingConfig_74:import61.NgbRatingConfig;
  __NgbTabsetConfig_75:import62.NgbTabsetConfig;
  __NgbTimepickerConfig_76:import63.NgbTimepickerConfig;
  __ROUTER_CONFIGURATION_77:any;
  __LocationStrategy_78:any;
  __Location_79:import64.Location;
  __UrlSerializer_80:import65.DefaultUrlSerializer;
  __RouterOutletMap_81:import66.RouterOutletMap;
  __NgModuleFactoryLoader_82:import67.SystemJsNgModuleLoader;
  __ROUTES_83:any[];
  __Router_84:any;
  __ActivatedRoute_85:any;
  _NoPreloading_86:import68.NoPreloading;
  _PreloadingStrategy_87:any;
  _RouterPreloader_88:import68.RouterPreloader;
  __PreloadAllModules_89:import68.PreloadAllModules;
  __ROUTER_INITIALIZER_90:any;
  __APP_BOOTSTRAP_LISTENER_91:any[];
  __menuService_92:import69.menuService;
  __NavService_93:import70.NavService;
  constructor(parent:import71.Injector) {
    super(parent,[
      import72.NgbAlertNgFactory,
      import73.NgbTooltipWindowNgFactory,
      import74.NgbTypeaheadWindowNgFactory,
      import75.NgbDatepickerNgFactory,
      import76.NgbModalBackdropNgFactory,
      import77.NgbModalWindowNgFactory,
      import78.NgbPopoverWindowNgFactory,
      import79.HomeComponentNgFactory,
      import80.SetupComponentNgFactory,
      import81.SettingsMenuComponentNgFactory,
      import82.WizardsComponentNgFactory,
      import83.TjjComponentNgFactory,
      import84.AppComponentNgFactory
    ]
    ,[import84.AppComponentNgFactory]);
  }
  get _LOCALE_ID_31():any {
    if ((this.__LOCALE_ID_31 == null)) { (this.__LOCALE_ID_31 = 'en-US'); }
    return this.__LOCALE_ID_31;
  }
  get _NgLocalization_32():import31.NgLocaleLocalization {
    if ((this.__NgLocalization_32 == null)) { (this.__NgLocalization_32 = new import31.NgLocaleLocalization(this._LOCALE_ID_31)); }
    return this.__NgLocalization_32;
  }
  get _ApplicationRef_37():any {
    if ((this.__ApplicationRef_37 == null)) { (this.__ApplicationRef_37 = this._ApplicationRef__36); }
    return this.__ApplicationRef_37;
  }
  get _Compiler_38():import35.Compiler {
    if ((this.__Compiler_38 == null)) { (this.__Compiler_38 = new import35.Compiler()); }
    return this.__Compiler_38;
  }
  get _APP_ID_39():any {
    if ((this.__APP_ID_39 == null)) { (this.__APP_ID_39 = import85._appIdRandomProviderFactory()); }
    return this.__APP_ID_39;
  }
  get _DOCUMENT_40():any {
    if ((this.__DOCUMENT_40 == null)) { (this.__DOCUMENT_40 = import4._document()); }
    return this.__DOCUMENT_40;
  }
  get _HAMMER_GESTURE_CONFIG_41():import36.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_41 == null)) { (this.__HAMMER_GESTURE_CONFIG_41 = new import36.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_41;
  }
  get _EVENT_MANAGER_PLUGINS_42():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_42 == null)) { (this.__EVENT_MANAGER_PLUGINS_42 = [
      new import86.DomEventsPlugin(),
      new import87.KeyEventsPlugin(),
      new import36.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_41)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_42;
  }
  get _EventManager_43():import37.EventManager {
    if ((this.__EventManager_43 == null)) { (this.__EventManager_43 = new import37.EventManager(this._EVENT_MANAGER_PLUGINS_42,this.parent.get(import88.NgZone))); }
    return this.__EventManager_43;
  }
  get _DomSharedStylesHost_44():import38.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_44 == null)) { (this.__DomSharedStylesHost_44 = new import38.DomSharedStylesHost(this._DOCUMENT_40)); }
    return this.__DomSharedStylesHost_44;
  }
  get _AnimationDriver_45():any {
    if ((this.__AnimationDriver_45 == null)) { (this.__AnimationDriver_45 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_45;
  }
  get _DomRootRenderer_46():import39.DomRootRenderer_ {
    if ((this.__DomRootRenderer_46 == null)) { (this.__DomRootRenderer_46 = new import39.DomRootRenderer_(this._DOCUMENT_40,this._EventManager_43,this._DomSharedStylesHost_44,this._AnimationDriver_45,this._APP_ID_39)); }
    return this.__DomRootRenderer_46;
  }
  get _NgProbeToken_47():any[] {
    if ((this.__NgProbeToken_47 == null)) { (this.__NgProbeToken_47 = [import24.routerNgProbeToken()]); }
    return this.__NgProbeToken_47;
  }
  get _RootRenderer_48():any {
    if ((this.__RootRenderer_48 == null)) { (this.__RootRenderer_48 = import89._createConditionalRootRenderer(this._DomRootRenderer_46,this.parent.get(import89.NgProbeToken,(null as any)),this._NgProbeToken_47)); }
    return this.__RootRenderer_48;
  }
  get _DomSanitizer_49():import40.DomSanitizerImpl {
    if ((this.__DomSanitizer_49 == null)) { (this.__DomSanitizer_49 = new import40.DomSanitizerImpl()); }
    return this.__DomSanitizer_49;
  }
  get _Sanitizer_50():any {
    if ((this.__Sanitizer_50 == null)) { (this.__Sanitizer_50 = this._DomSanitizer_49); }
    return this.__Sanitizer_50;
  }
  get _AnimationQueue_51():import41.AnimationQueue {
    if ((this.__AnimationQueue_51 == null)) { (this.__AnimationQueue_51 = new import41.AnimationQueue(this.parent.get(import88.NgZone))); }
    return this.__AnimationQueue_51;
  }
  get _ViewUtils_52():import42.ViewUtils {
    if ((this.__ViewUtils_52 == null)) { (this.__ViewUtils_52 = new import42.ViewUtils(this._RootRenderer_48,this._Sanitizer_50,this._AnimationQueue_51)); }
    return this.__ViewUtils_52;
  }
  get _IterableDiffers_53():any {
    if ((this.__IterableDiffers_53 == null)) { (this.__IterableDiffers_53 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_53;
  }
  get _KeyValueDiffers_54():any {
    if ((this.__KeyValueDiffers_54 == null)) { (this.__KeyValueDiffers_54 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_54;
  }
  get _SharedStylesHost_55():any {
    if ((this.__SharedStylesHost_55 == null)) { (this.__SharedStylesHost_55 = this._DomSharedStylesHost_44); }
    return this.__SharedStylesHost_55;
  }
  get _Title_56():import43.Title {
    if ((this.__Title_56 == null)) { (this.__Title_56 = new import43.Title()); }
    return this.__Title_56;
  }
  get _RadioControlRegistry_57():import44.RadioControlRegistry {
    if ((this.__RadioControlRegistry_57 == null)) { (this.__RadioControlRegistry_57 = new import44.RadioControlRegistry()); }
    return this.__RadioControlRegistry_57;
  }
  get _NgbModalStack_58():import45.NgbModalStack {
    if ((this.__NgbModalStack_58 == null)) { (this.__NgbModalStack_58 = new import45.NgbModalStack()); }
    return this.__NgbModalStack_58;
  }
  get _NgbModal_59():import46.NgbModal {
    if ((this.__NgbModal_59 == null)) { (this.__NgbModal_59 = new import46.NgbModal(this,this,this._NgbModalStack_58)); }
    return this.__NgbModal_59;
  }
  get _NgbAlertConfig_60():import47.NgbAlertConfig {
    if ((this.__NgbAlertConfig_60 == null)) { (this.__NgbAlertConfig_60 = new import47.NgbAlertConfig()); }
    return this.__NgbAlertConfig_60;
  }
  get _NgbProgressbarConfig_61():import48.NgbProgressbarConfig {
    if ((this.__NgbProgressbarConfig_61 == null)) { (this.__NgbProgressbarConfig_61 = new import48.NgbProgressbarConfig()); }
    return this.__NgbProgressbarConfig_61;
  }
  get _NgbTooltipConfig_62():import49.NgbTooltipConfig {
    if ((this.__NgbTooltipConfig_62 == null)) { (this.__NgbTooltipConfig_62 = new import49.NgbTooltipConfig()); }
    return this.__NgbTooltipConfig_62;
  }
  get _NgbTypeaheadConfig_63():import50.NgbTypeaheadConfig {
    if ((this.__NgbTypeaheadConfig_63 == null)) { (this.__NgbTypeaheadConfig_63 = new import50.NgbTypeaheadConfig()); }
    return this.__NgbTypeaheadConfig_63;
  }
  get _NgbAccordionConfig_64():import51.NgbAccordionConfig {
    if ((this.__NgbAccordionConfig_64 == null)) { (this.__NgbAccordionConfig_64 = new import51.NgbAccordionConfig()); }
    return this.__NgbAccordionConfig_64;
  }
  get _NgbCarouselConfig_65():import52.NgbCarouselConfig {
    if ((this.__NgbCarouselConfig_65 == null)) { (this.__NgbCarouselConfig_65 = new import52.NgbCarouselConfig()); }
    return this.__NgbCarouselConfig_65;
  }
  get _NgbCalendar_66():import53.NgbCalendarGregorian {
    if ((this.__NgbCalendar_66 == null)) { (this.__NgbCalendar_66 = new import53.NgbCalendarGregorian()); }
    return this.__NgbCalendar_66;
  }
  get _NgbDatepickerI18n_67():import54.NgbDatepickerI18nDefault {
    if ((this.__NgbDatepickerI18n_67 == null)) { (this.__NgbDatepickerI18n_67 = new import54.NgbDatepickerI18nDefault()); }
    return this.__NgbDatepickerI18n_67;
  }
  get _NgbDateParserFormatter_68():import55.NgbDateISOParserFormatter {
    if ((this.__NgbDateParserFormatter_68 == null)) { (this.__NgbDateParserFormatter_68 = new import55.NgbDateISOParserFormatter()); }
    return this.__NgbDateParserFormatter_68;
  }
  get _NgbDatepickerService_69():import56.NgbDatepickerService {
    if ((this.__NgbDatepickerService_69 == null)) { (this.__NgbDatepickerService_69 = new import56.NgbDatepickerService(this._NgbCalendar_66)); }
    return this.__NgbDatepickerService_69;
  }
  get _NgbDatepickerConfig_70():import57.NgbDatepickerConfig {
    if ((this.__NgbDatepickerConfig_70 == null)) { (this.__NgbDatepickerConfig_70 = new import57.NgbDatepickerConfig()); }
    return this.__NgbDatepickerConfig_70;
  }
  get _NgbDropdownConfig_71():import58.NgbDropdownConfig {
    if ((this.__NgbDropdownConfig_71 == null)) { (this.__NgbDropdownConfig_71 = new import58.NgbDropdownConfig()); }
    return this.__NgbDropdownConfig_71;
  }
  get _NgbPaginationConfig_72():import59.NgbPaginationConfig {
    if ((this.__NgbPaginationConfig_72 == null)) { (this.__NgbPaginationConfig_72 = new import59.NgbPaginationConfig()); }
    return this.__NgbPaginationConfig_72;
  }
  get _NgbPopoverConfig_73():import60.NgbPopoverConfig {
    if ((this.__NgbPopoverConfig_73 == null)) { (this.__NgbPopoverConfig_73 = new import60.NgbPopoverConfig()); }
    return this.__NgbPopoverConfig_73;
  }
  get _NgbRatingConfig_74():import61.NgbRatingConfig {
    if ((this.__NgbRatingConfig_74 == null)) { (this.__NgbRatingConfig_74 = new import61.NgbRatingConfig()); }
    return this.__NgbRatingConfig_74;
  }
  get _NgbTabsetConfig_75():import62.NgbTabsetConfig {
    if ((this.__NgbTabsetConfig_75 == null)) { (this.__NgbTabsetConfig_75 = new import62.NgbTabsetConfig()); }
    return this.__NgbTabsetConfig_75;
  }
  get _NgbTimepickerConfig_76():import63.NgbTimepickerConfig {
    if ((this.__NgbTimepickerConfig_76 == null)) { (this.__NgbTimepickerConfig_76 = new import63.NgbTimepickerConfig()); }
    return this.__NgbTimepickerConfig_76;
  }
  get _ROUTER_CONFIGURATION_77():any {
    if ((this.__ROUTER_CONFIGURATION_77 == null)) { (this.__ROUTER_CONFIGURATION_77 = {}); }
    return this.__ROUTER_CONFIGURATION_77;
  }
  get _LocationStrategy_78():any {
    if ((this.__LocationStrategy_78 == null)) { (this.__LocationStrategy_78 = import24.provideLocationStrategy(this.parent.get(import90.PlatformLocation),this.parent.get(import91.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_77)); }
    return this.__LocationStrategy_78;
  }
  get _Location_79():import64.Location {
    if ((this.__Location_79 == null)) { (this.__Location_79 = new import64.Location(this._LocationStrategy_78)); }
    return this.__Location_79;
  }
  get _UrlSerializer_80():import65.DefaultUrlSerializer {
    if ((this.__UrlSerializer_80 == null)) { (this.__UrlSerializer_80 = new import65.DefaultUrlSerializer()); }
    return this.__UrlSerializer_80;
  }
  get _RouterOutletMap_81():import66.RouterOutletMap {
    if ((this.__RouterOutletMap_81 == null)) { (this.__RouterOutletMap_81 = new import66.RouterOutletMap()); }
    return this.__RouterOutletMap_81;
  }
  get _NgModuleFactoryLoader_82():import67.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_82 == null)) { (this.__NgModuleFactoryLoader_82 = new import67.SystemJsNgModuleLoader(this._Compiler_38,this.parent.get(import67.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_82;
  }
  get _ROUTES_83():any[] {
    if ((this.__ROUTES_83 == null)) { (this.__ROUTES_83 = [
        [{
          path: '',
          redirectTo: 'home',
          pathMatch: 'full'
        }
      ],
        [{
          path: 'home',
          component: import92.HomeComponent
        }
      ],
      [
        {
          path: 'wizardsMenu',
          component: import93.SetupComponent,
            children: [{
              path: '',
              component: import94.SettingsMenuComponent
            }
          ]
        }
        ,
        {
          path: 'wizardsMenus',
          component: import95.WizardsComponent,
            children: [{
              path: 'upgradewizard',
              component: import96.TjjComponent
            }
          ]
        }
        ,
        {
          path: 'settingsMenu',
          component: import93.SetupComponent,
          children: [
            {
              path: '',
              component: import94.SettingsMenuComponent
            }
            ,
            {
              path: 'linemovement',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'printtrigger',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'poweroptions',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'positionorientation',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'content',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'properties',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'clocksdates',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'printheadmanualmode',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'inksystemmanualmode',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'inkdetails',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'hardware',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'gutter',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'installoptions',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'status',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'logs',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'qualityproblems',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'jetprofile',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'tests',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'modulation',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'pressurelogs',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'testprint',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'installation',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'inspection',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'configueralerts',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'rangedalerts',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'emailalerts',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'servicealerts',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'setup',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'assignment',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'monitor',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'test',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'labelselect',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'ethernet',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'serial',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'advanced',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'languagekeyboard',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'datetime',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'backup',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'restore',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'defaults',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'upgrade',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'upgradeconfigur',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'overview',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'softwareversions',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'printerconnection',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'languageandkey',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'accessibility',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'diagnostics',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'network',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'versioninformation',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'logoeditor',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'installpacks',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'migratepacks',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'consumables',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'counters',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'statistics',
              component: import96.TjjComponent
            }
            ,
            {
              path: 'inspectionp',
              component: import96.TjjComponent
            }

          ]

        }

      ]

    ]
    ); }
    return this.__ROUTES_83;
  }
  get _Router_84():any {
    if ((this.__Router_84 == null)) { (this.__Router_84 = import24.setupRouter(this._ApplicationRef_37,this._UrlSerializer_80,this._RouterOutletMap_81,this._Location_79,this,this._NgModuleFactoryLoader_82,this._Compiler_38,this._ROUTES_83,this._ROUTER_CONFIGURATION_77,this.parent.get(import97.UrlHandlingStrategy,(null as any)),this.parent.get(import98.RouteReuseStrategy,(null as any)))); }
    return this.__Router_84;
  }
  get _ActivatedRoute_85():any {
    if ((this.__ActivatedRoute_85 == null)) { (this.__ActivatedRoute_85 = import24.rootRoute(this._Router_84)); }
    return this.__ActivatedRoute_85;
  }
  get _PreloadAllModules_89():import68.PreloadAllModules {
    if ((this.__PreloadAllModules_89 == null)) { (this.__PreloadAllModules_89 = new import68.PreloadAllModules()); }
    return this.__PreloadAllModules_89;
  }
  get _ROUTER_INITIALIZER_90():any {
    if ((this.__ROUTER_INITIALIZER_90 == null)) { (this.__ROUTER_INITIALIZER_90 = import24.initialRouterNavigation(this._Router_84,this._ApplicationRef_37,this._RouterPreloader_88,this._ROUTER_CONFIGURATION_77)); }
    return this.__ROUTER_INITIALIZER_90;
  }
  get _APP_BOOTSTRAP_LISTENER_91():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_91 == null)) { (this.__APP_BOOTSTRAP_LISTENER_91 = [this._ROUTER_INITIALIZER_90]); }
    return this.__APP_BOOTSTRAP_LISTENER_91;
  }
  get _menuService_92():import69.menuService {
    if ((this.__menuService_92 == null)) { (this.__menuService_92 = new import69.menuService()); }
    return this.__menuService_92;
  }
  get _NavService_93():import70.NavService {
    if ((this.__NavService_93 == null)) { (this.__NavService_93 = new import70.NavService()); }
    return this.__NavService_93;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._NgbAlertModule_3 = new import5.NgbAlertModule();
    this._NgbButtonsModule_4 = new import6.NgbButtonsModule();
    this._NgbCollapseModule_5 = new import7.NgbCollapseModule();
    this._NgbProgressbarModule_6 = new import8.NgbProgressbarModule();
    this._NgbTooltipModule_7 = new import9.NgbTooltipModule();
    this._NgbTypeaheadModule_8 = new import10.NgbTypeaheadModule();
    this._NgbAccordionModule_9 = new import11.NgbAccordionModule();
    this._NgbCarouselModule_10 = new import12.NgbCarouselModule();
    this._InternalFormsSharedModule_11 = new import13.InternalFormsSharedModule();
    this._FormsModule_12 = new import14.FormsModule();
    this._NgbDatepickerModule_13 = new import15.NgbDatepickerModule();
    this._NgbDropdownModule_14 = new import16.NgbDropdownModule();
    this._NgbModalModule_15 = new import17.NgbModalModule();
    this._NgbPaginationModule_16 = new import18.NgbPaginationModule();
    this._NgbPopoverModule_17 = new import19.NgbPopoverModule();
    this._NgbRatingModule_18 = new import20.NgbRatingModule();
    this._NgbTabsetModule_19 = new import21.NgbTabsetModule();
    this._NgbTimepickerModule_20 = new import22.NgbTimepickerModule();
    this._NgbRootModule_21 = new import23.NgbRootModule();
    this._ROUTER_FORROOT_GUARD_22 = import24.provideForRootGuard(this.parent.get(import99.Router,(null as any)));
    this._RouterModule_23 = new import24.RouterModule(this._ROUTER_FORROOT_GUARD_22);
    this._CrisisCenterRoutingModule_24 = new import25.CrisisCenterRoutingModule();
    this._HomeRoutingModule_25 = new import26.HomeRoutingModule();
    this._HomeModule_26 = new import27.HomeModule();
    this._SetupRoutingModule_27 = new import28.SetupRoutingModule();
    this._SharedModule_28 = new import29.SharedModule();
    this._Setup_29 = new import30.Setup();
    this._AppModule_30 = new import1.AppModule();
    this._ErrorHandler_33 = import4.errorHandler();
    this._ApplicationInitStatus_34 = new import32.ApplicationInitStatus(this.parent.get(import32.APP_INITIALIZER,(null as any)));
    this._Testability_35 = new import33.Testability(this.parent.get(import88.NgZone));
    this._ApplicationRef__36 = new import34.ApplicationRef_(this.parent.get(import88.NgZone),this.parent.get(import100.Console),this,this._ErrorHandler_33,this,this._ApplicationInitStatus_34,this.parent.get(import33.TestabilityRegistry,(null as any)),this._Testability_35);
    this._NoPreloading_86 = new import68.NoPreloading();
    this._PreloadingStrategy_87 = this._NoPreloading_86;
    this._RouterPreloader_88 = new import68.RouterPreloader(this._Router_84,this._NgModuleFactoryLoader_82,this._Compiler_38,this,this._PreloadingStrategy_87);
    return this._AppModule_30;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.NgbAlertModule)) { return this._NgbAlertModule_3; }
    if ((token === import6.NgbButtonsModule)) { return this._NgbButtonsModule_4; }
    if ((token === import7.NgbCollapseModule)) { return this._NgbCollapseModule_5; }
    if ((token === import8.NgbProgressbarModule)) { return this._NgbProgressbarModule_6; }
    if ((token === import9.NgbTooltipModule)) { return this._NgbTooltipModule_7; }
    if ((token === import10.NgbTypeaheadModule)) { return this._NgbTypeaheadModule_8; }
    if ((token === import11.NgbAccordionModule)) { return this._NgbAccordionModule_9; }
    if ((token === import12.NgbCarouselModule)) { return this._NgbCarouselModule_10; }
    if ((token === import13.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_11; }
    if ((token === import14.FormsModule)) { return this._FormsModule_12; }
    if ((token === import15.NgbDatepickerModule)) { return this._NgbDatepickerModule_13; }
    if ((token === import16.NgbDropdownModule)) { return this._NgbDropdownModule_14; }
    if ((token === import17.NgbModalModule)) { return this._NgbModalModule_15; }
    if ((token === import18.NgbPaginationModule)) { return this._NgbPaginationModule_16; }
    if ((token === import19.NgbPopoverModule)) { return this._NgbPopoverModule_17; }
    if ((token === import20.NgbRatingModule)) { return this._NgbRatingModule_18; }
    if ((token === import21.NgbTabsetModule)) { return this._NgbTabsetModule_19; }
    if ((token === import22.NgbTimepickerModule)) { return this._NgbTimepickerModule_20; }
    if ((token === import23.NgbRootModule)) { return this._NgbRootModule_21; }
    if ((token === import24.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_22; }
    if ((token === import24.RouterModule)) { return this._RouterModule_23; }
    if ((token === import25.CrisisCenterRoutingModule)) { return this._CrisisCenterRoutingModule_24; }
    if ((token === import26.HomeRoutingModule)) { return this._HomeRoutingModule_25; }
    if ((token === import27.HomeModule)) { return this._HomeModule_26; }
    if ((token === import28.SetupRoutingModule)) { return this._SetupRoutingModule_27; }
    if ((token === import29.SharedModule)) { return this._SharedModule_28; }
    if ((token === import30.Setup)) { return this._Setup_29; }
    if ((token === import1.AppModule)) { return this._AppModule_30; }
    if ((token === import101.LOCALE_ID)) { return this._LOCALE_ID_31; }
    if ((token === import31.NgLocalization)) { return this._NgLocalization_32; }
    if ((token === import102.ErrorHandler)) { return this._ErrorHandler_33; }
    if ((token === import32.ApplicationInitStatus)) { return this._ApplicationInitStatus_34; }
    if ((token === import33.Testability)) { return this._Testability_35; }
    if ((token === import34.ApplicationRef_)) { return this._ApplicationRef__36; }
    if ((token === import34.ApplicationRef)) { return this._ApplicationRef_37; }
    if ((token === import35.Compiler)) { return this._Compiler_38; }
    if ((token === import85.APP_ID)) { return this._APP_ID_39; }
    if ((token === import103.DOCUMENT)) { return this._DOCUMENT_40; }
    if ((token === import36.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_41; }
    if ((token === import37.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_42; }
    if ((token === import37.EventManager)) { return this._EventManager_43; }
    if ((token === import38.DomSharedStylesHost)) { return this._DomSharedStylesHost_44; }
    if ((token === import104.AnimationDriver)) { return this._AnimationDriver_45; }
    if ((token === import39.DomRootRenderer)) { return this._DomRootRenderer_46; }
    if ((token === import34.NgProbeToken)) { return this._NgProbeToken_47; }
    if ((token === import105.RootRenderer)) { return this._RootRenderer_48; }
    if ((token === import40.DomSanitizer)) { return this._DomSanitizer_49; }
    if ((token === import106.Sanitizer)) { return this._Sanitizer_50; }
    if ((token === import41.AnimationQueue)) { return this._AnimationQueue_51; }
    if ((token === import42.ViewUtils)) { return this._ViewUtils_52; }
    if ((token === import107.IterableDiffers)) { return this._IterableDiffers_53; }
    if ((token === import108.KeyValueDiffers)) { return this._KeyValueDiffers_54; }
    if ((token === import38.SharedStylesHost)) { return this._SharedStylesHost_55; }
    if ((token === import43.Title)) { return this._Title_56; }
    if ((token === import44.RadioControlRegistry)) { return this._RadioControlRegistry_57; }
    if ((token === import45.NgbModalStack)) { return this._NgbModalStack_58; }
    if ((token === import46.NgbModal)) { return this._NgbModal_59; }
    if ((token === import47.NgbAlertConfig)) { return this._NgbAlertConfig_60; }
    if ((token === import48.NgbProgressbarConfig)) { return this._NgbProgressbarConfig_61; }
    if ((token === import49.NgbTooltipConfig)) { return this._NgbTooltipConfig_62; }
    if ((token === import50.NgbTypeaheadConfig)) { return this._NgbTypeaheadConfig_63; }
    if ((token === import51.NgbAccordionConfig)) { return this._NgbAccordionConfig_64; }
    if ((token === import52.NgbCarouselConfig)) { return this._NgbCarouselConfig_65; }
    if ((token === import53.NgbCalendar)) { return this._NgbCalendar_66; }
    if ((token === import54.NgbDatepickerI18n)) { return this._NgbDatepickerI18n_67; }
    if ((token === import55.NgbDateParserFormatter)) { return this._NgbDateParserFormatter_68; }
    if ((token === import56.NgbDatepickerService)) { return this._NgbDatepickerService_69; }
    if ((token === import57.NgbDatepickerConfig)) { return this._NgbDatepickerConfig_70; }
    if ((token === import58.NgbDropdownConfig)) { return this._NgbDropdownConfig_71; }
    if ((token === import59.NgbPaginationConfig)) { return this._NgbPaginationConfig_72; }
    if ((token === import60.NgbPopoverConfig)) { return this._NgbPopoverConfig_73; }
    if ((token === import61.NgbRatingConfig)) { return this._NgbRatingConfig_74; }
    if ((token === import62.NgbTabsetConfig)) { return this._NgbTabsetConfig_75; }
    if ((token === import63.NgbTimepickerConfig)) { return this._NgbTimepickerConfig_76; }
    if ((token === import24.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_77; }
    if ((token === import91.LocationStrategy)) { return this._LocationStrategy_78; }
    if ((token === import64.Location)) { return this._Location_79; }
    if ((token === import65.UrlSerializer)) { return this._UrlSerializer_80; }
    if ((token === import66.RouterOutletMap)) { return this._RouterOutletMap_81; }
    if ((token === import109.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_82; }
    if ((token === import110.ROUTES)) { return this._ROUTES_83; }
    if ((token === import99.Router)) { return this._Router_84; }
    if ((token === import111.ActivatedRoute)) { return this._ActivatedRoute_85; }
    if ((token === import68.NoPreloading)) { return this._NoPreloading_86; }
    if ((token === import68.PreloadingStrategy)) { return this._PreloadingStrategy_87; }
    if ((token === import68.RouterPreloader)) { return this._RouterPreloader_88; }
    if ((token === import68.PreloadAllModules)) { return this._PreloadAllModules_89; }
    if ((token === import24.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_90; }
    if ((token === import85.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_91; }
    if ((token === import69.menuService)) { return this._menuService_92; }
    if ((token === import70.NavService)) { return this._NavService_93; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__36.ngOnDestroy();
    this._RouterPreloader_88.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);