/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../app/home/home.module';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '../../../app/home/home-routing.module';
import * as import4 from '@angular/core/src/di/injector';
import * as import5 from './home.component.ngfactory';
import * as import6 from '../../../app/home/home.component';
import * as import7 from '@angular/router/src/router_config_loader';
class HomeModuleInjector extends import0.NgModuleInjector<import1.HomeModule> {
  _RouterModule_0:import2.RouterModule;
  _HomeRoutingModule_1:import3.HomeRoutingModule;
  _HomeModule_2:import1.HomeModule;
  __ROUTES_3:any[];
  constructor(parent:import4.Injector) {
    super(parent,[import5.HomeComponentNgFactory],([] as any[]));
  }
  get _ROUTES_3():any[] {
        if ((this.__ROUTES_3 == null)) { (this.__ROUTES_3 = [[{
          path: 'home',
          component: import6.HomeComponent
        }
    ]]); }
    return this.__ROUTES_3;
  }
  createInternal():import1.HomeModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ROUTER_FORROOT_GUARD,(null as any)));
    this._HomeRoutingModule_1 = new import3.HomeRoutingModule();
    this._HomeModule_2 = new import1.HomeModule();
    return this._HomeModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.HomeRoutingModule)) { return this._HomeRoutingModule_1; }
    if ((token === import1.HomeModule)) { return this._HomeModule_2; }
    if ((token === import7.ROUTES)) { return this._ROUTES_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const HomeModuleNgFactory:import0.NgModuleFactory<import1.HomeModule> = new import0.NgModuleFactory(HomeModuleInjector,import1.HomeModule);